[profile.default]
solc_version = "0.8.19"
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@openzeppelin=lib/openzeppelin-contracts@v4.8.3',
    '@tropykus=lib/protocol-rsk',
]
[fuzz]
runs = 1000
[invariant]
runs = 64
depth = 512
# depth = 10            # For forge coverage
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
